"""Test tools for processor-flow integration testing."""

import logging
from typing import Any

logger = logging.getLogger(__name__)


async def dummy_search_task(
    file_ids: list[str],
    questions: list[dict[str, Any]],
    **kwargs: Any,
) -> dict[str, Any]:
    """Dummy search task that simulates searching documents for questions.
    
    Args:
        file_ids: List of file IDs to search
        questions: List of question dictionaries
        
    Returns:
        Dictionary with search results for each question
    """
    logger.info(
        "dummy_search_task: Processing %d files and %d questions",
        len(file_ids),
        len(questions),
    )
    
    results = []
    for question in questions:
        q_id = question.get("id", "unknown")
        q_text = question.get("question", "")
        
        # Simulate search results
        result = {
            "question_id": q_id,
            "question": q_text,
            "context": f"Dummy context found for question '{q_text}' in {len(file_ids)} files",
            "relevance_score": 0.95,
        }
        results.append(result)
        
    logger.info("dummy_search_task: Returning %d results", len(results))
    return {"search_results": results}


async def dummy_answer_task(
    questions: list[dict[str, Any]],
    search_results: list[dict[str, Any]],
    **kwargs: Any,
) -> dict[str, Any]:
    """Dummy answer task that formats search results into answers.
    
    Args:
        questions: List of question dictionaries
        search_results: Search results from previous task
        
    Returns:
        Dictionary with formatted answers matching OutputMapper expectations
    """
    logger.info(
        "dummy_answer_task: Generating answers for %d questions",
        len(questions),
    )
    
    answers = []
    for question in questions:
        q_id = question.get("id", "unknown")
        q_text = question.get("question", "")
        expected = question.get("expectedAnswer", "")
        input_q_ids = question.get("inputQuestionIds", [])
        
        # Find matching search result
        search_result = next(
            (r for r in search_results if r.get("question_id") == q_id),
            None,
        )
        
        context = search_result.get("context", "No context found") if search_result else "No context found"
        
        # Create answer in the format expected by OutputMapper
        answer = {
            "id": q_id,
            "question": q_text,
            "expectedAnswer": expected,
            "sourcedContent": f"ANSWER: This is a test answer for '{q_text}'. {context}",
            "explanation": f"This answer was generated by the dummy_answer_task for testing purposes.",
            "answerValidity": 1.0,
            "validityExplanation": "Test answer - always valid",
            "annotations": [],
            "inputQuestionIds": input_q_ids,
        }
        answers.append(answer)
        
    logger.info("dummy_answer_task: Returning %d answers", len(answers))
    return {"answers": answers}


# Registry of test tools
TEST_TOOLS_REGISTRY = {
    "dummy_search_task": dummy_search_task,
    "dummy_answer_task": dummy_answer_task,
}





