# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: clark-protos/processors/customWorkflow.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from clark_protos.models import file_pb2 as clark__protos_dot_models_dot_file__pb2
from clark_protos.processors import questionAnswering_pb2 as clark__protos_dot_processors_dot_questionAnswering__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n,clark-protos/processors/customWorkflow.proto\x12\x14\x62iolevate.processors\x1a\x1e\x63lark-protos/models/file.proto\x1a/clark-protos/processors/questionAnswering.proto\"\x89\x02\n\x1dProcessorCustomWorkflowConfig\x12\x36\n\x12\x66irst_source_files\x18\x01 \x03(\x0b\x32\x1a.clark.models.FileMetaData\x12\x37\n\x13second_source_files\x18\x02 \x03(\x0b\x32\x1a.clark.models.FileMetaData\x12\x31\n\tquestions\x18\x03 \x03(\x0b\x32\x1e.biolevate.processors.Question\x12\x13\n\x0bworkflow_id\x18\x04 \x01(\t\x12\x19\n\x11\x61\x64\x64itional_inputs\x18\x05 \x01(\t\x12\x14\n\x0c\x63ollectionId\x18\x06 \x01(\t\"l\n\x1dProcessorCustomWorkflowOutput\x12\x35\n\x07\x61nswers\x18\x01 \x03(\x0b\x32$.biolevate.processors.QuestionAnswer\x12\x14\n\x0c\x63ollectionId\x18\x02 \x01(\tBE\n#com.biolevate.server.gen.processorsB\x1cProcessorCustomWorkflowProtoP\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'clark_protos.processors.customWorkflow_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  _globals['DESCRIPTOR']._options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n#com.biolevate.server.gen.processorsB\034ProcessorCustomWorkflowProtoP\001'
  _globals['_PROCESSORCUSTOMWORKFLOWCONFIG']._serialized_start=152
  _globals['_PROCESSORCUSTOMWORKFLOWCONFIG']._serialized_end=417
  _globals['_PROCESSORCUSTOMWORKFLOWOUTPUT']._serialized_start=419
  _globals['_PROCESSORCUSTOMWORKFLOWOUTPUT']._serialized_end=527
# @@protoc_insertion_point(module_scope)
